### ISSUE TITLE
Agent-agent Evaluation

### ISSUE THREAD

**Issue by upasana27** [sjtu-marl/ZSC-Eval#1]
Hello! I had a question regarding the evaluation. Is it possible to evaluate the baselines against each other i.e. FCP vs FCP?

**Comment by xihuai18** [comment]
Sure, you can just change the yamls

**Comment by upasana27** [comment]
Thank you for the reply. I couldn't find the yaml for the baselines when I downloaded the pre-trained agents using this command: git clone https://huggingface.co/Leoxxxxh/ZSC-Eval-policy_pool policy_pool
Is there a way to get the yaml?

**Comment by xihuai18** [comment]
https://github.com/sjtu-marl/ZSC-Eval?tab=readme-ov-file#prepare-the-evaluation-partners

You can generate the yamls following this guide.

**Comment by upasana27** [comment]
I am not sure if I understand. It seems like the guide attached is to create yaml for biased evaluation partners . However, my question is whether I can evaluate FCP agent vs FCP agent. Please let me know if that is what you meant as well.

**Comment by xihuai18** [comment]
Generate the default yamls (I did not provide them since the file paths contain some private information) and then change them into FCP model paths for evaluation.

**Comment by xihuai18** [comment]
Besides, I provide all training files needed in random3_m for reference. 
https://huggingface.co/Leoxxxxh/ZSC-Eval-policy_pool/tree/main/random3_m

**Comment by xihuai18** [comment]
Or you can just change the benchmark yamls, e.g., https://huggingface.co/Leoxxxxh/ZSC-Eval-policy_pool/blob/main/random3/hsp/s1/hsp/benchmarks-s20.yml

Change the biased agents to FCP agent and evaluation FCP agents using the yaml.

**Comment by upasana27** [comment]
Thanks a lot for the reply. To clarify what I need to change, in the code below, I need to change the actor to the path of the fcp agent (assuming I can use mid as 24 and final as 36). However, I do see that there are 5 seeds of the same for each stage as in https://huggingface.co/Leoxxxxh/ZSC-Eval-policy_pool/tree/main/random3/fcp/s2/fcp-S2-s12. Can you please clarify how to edit the benchmark yaml? I need to change it for all the baseline agents as well, so I need to know exactly what the yaml is reflecting to be able to do it for all the baselines. 
Thanks for all the help!
bias2_mid:
    policy_config_path: random3/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random3/hsp/s1/hsp/hsp34_mid_w0_actor.pt
bias2_final:
    policy_config_path: random3/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    train: False
    model_path:
        actor: random3/hsp/s1/hsp/hsp34_final_w0_actor.pt

**Comment by xihuai18** [comment]
https://github.com/sjtu-marl/ZSC-Eval/blob/master/zsceval/scripts/overcooked/shell/eval_with_bias_agents.sh

This shell may make it clear the usage of the benchmark yamls.

**Comment by upasana27** [comment]
Ok, thanks.

**Comment by upasana27** [comment]
![Screenshot from 2024-10-05 15-24-11](https://github.com/user-attachments/assets/520afcf2-9d27-42f4-b5ad-04e250cd6e91)

- I am getting this error which seems like it has something to do with the dummy batch variable in the eval script. Would you have any idea on how to fix this?

**Comment by upasana27** [comment]
Thanks for the help, I am able to evaluate agent vs agent now. Am I able to find the trajectory saved somewhere?

**Comment by upasana27** [comment]
Thanks for your help, I am able to run the agent-vs-agent evaluation now. I wanted to ask if we can get the trajectory of the agents from this repository, i.e. the player states and joint-action at each timestep

**Comment by upasana27** [comment]
Thanks for your help, I am able to run the agent vs agent evaluation code now. I am running into some assertion errors though, particular in the https://github.com/sjtu-marl/ZSC-Eval/blob/master/zsceval/scripts/overcooked/eval/eval_with_population.py, in line 207 and line 208:
assert all_args.n_eval_rollout_threads % (num_population_agents * 2) == 0, num_population_agents
assert all_args.eval_episodes % all_args.n_eval_rollout_threads == 0
Can you please clarify what the arguments n_eval_rollout_threads and eval_episodes mean in this context?

**Comment by xihuai18** [comment]
For these basic issues, carefully reviewing the code can solve them.
